### ISSUE TITLE
E_ERROR SettingsBase

### ISSUE THREAD

**Issue by TorinAsakura** [mihdan/cyr2lat#102]
Привет ребят.

Не знаю что это должно было сломать, но, пока, вроде, всё работает.

Прикладываю лог и базовую инфу о сбое.

Версия WordPress 5.8
Текущая тема: Follow The Compass (версия 2.0.0)
Проблемный плагин: Cyr-To-Lat (версия 5.1.0)
Версия PHP 7.4.14

Подробности ошибки
===================================
Ошибка с типом E_ERROR возникла на строке 401 файла /var/www/u1055818/data/www/followthecompass.ru/wp-content/plugins/cyr2lat/src/php/Settings/Abstracts/SettingsBase.php. Сообщение об ошибке: Uncaught Error: Call to undefined function Cyr_To_Lat\Settings\Abstracts\add_settings_section() in /var/www/u1055818/data/www/followthecompass.ru/wp-content/plugins/cyr2lat/src/php/Settings/Abstracts/SettingsBase.php:401
Stack trace:
#0 /var/www/u1055818/data/www/followthecompass.ru/wp-includes/class-wp-hook.php(303): Cyr_To_Lat\Settings\Abstracts\SettingsBase->setup_tabs_section(Object(WP_Screen))
#1 /var/www/u1055818/data/www/followthecompass.ru/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#2 /var/www/u1055818/data/www/followthecompass.ru/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /var/www/u1055818/data/www/followthecompass.ru/wp-admin/includes/class-wp-screen.php(421): do_action('current_screen', Object(WP_Screen))
#4 /var/www/u1055818/data/www/followthecompass.ru/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()
#5 /var/www/u1055818/data/www/followthecompass.ru/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-sender.php(414): set_

**Comment by kagg-design** [comment]
Спасибо за сообщение.

Это проблема jetpack. Исправлено в 5cc8ee048200697e387f741a8eab6d00a9acf7a5 там есть и пояснение в комментарии. Выпустим в 5.2.2.
