### ISSUE TITLE
Поддержка WP-Recall

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#11]

**Comment by mihdan** [comment]
Для wp-recall есть [свой аддон](https://github.com/Otshelnik-Fm/otfm-rus-to-lat)

**Comment by Otshelnik-Fm** [comment]
Можно ставить и cyr2lat - плагин умеет и его. Но я выпустил тот доп - т.к. для внутренних целей таблица транслитерации есть в реколл. Если сравнивать ваше решение и мое - разницы то почти и нет. Единственное: вы фишки, вроде настроек в админку добавили. Старые слаги конвертировать можете. У моего допа все скромней - включил и работай. Но он никак не сможет существующие слаги поменять. Когда сайт с ноля - это и не требуется.

**Comment by mihdan** [comment]
Ну я поглядел твой аддон и не знаю, нужно ли у нас делать поддержку или нет. Старые слаги, да, умеем. Сделаем еще очередь заданий, если слагов много. Сделаем WP-CLI, чтобы из консоли запускать генерацию слагов. @Otshelnik-Fm
