### ISSUE TITLE
После включения плагина термины (метки, рубрики) на кириллице отдают 404

### ISSUE THREAD

**Issue by campusboy87** [mihdan/cyr2lat#118]
Приветствую. На старом стайте имеются рубрики и метки на кириллице. После включения плагина эти термины начинают отдавать 404 ошибку. Подобная проблема воспроизводится и на чистой установке WP.

Тестировал на чистой установке:
* WordPress 5.9.3
* Twenty Nineteen 2.2.
* Cyr-To-Lat 5.2.7

Глубоко не копался, потому что может так и должно быть и это специально запрограммированное поведение? Пока заказчик не очень хочет всё конвертировать в латиницу и делать 301 редиректы (пытаюсь склонить его к этому варианту, считаю это наиболее верным решением). Но как план Б вынужден изучить ситуацию, можно ли это "исправить"? Сильно глубоко пока не копался, всё что успел выяснить:

* Если в коде плагина отключить (закомментировать) фильтр `sanitize_title`, то всё начинает работать как надо.
* Если в методе `sanitize_title` переопределить `$this->is_term` из `false` в `true`, то всё начинает работать как надо.

На всякий случай кидаю скриншоты с данными до и после включение плагина. В тестах используется метка со slug `метка-1` или `%d0%bc%d0%b5%d1%82%d0%ba%d0%b0-1`.

Метка открывается по адресу (при включённом или отключённом плагине) по адресу
https://домен/tags/%d0%bc%d0%b5%d1%82%d0%ba%d0%b0-1/

## Плагин не включён
![image](https://user-images.githubusercontent.com/20075333/166171308-a2f16382-f75c-499d-be8d-bbd943c571ec.png)
```sql
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id)
WHERE 1=1
AND ( wp_term_relationships.term_taxonomy_id IN (541) )
AND ((wp_posts.post_type = 'post'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'private')))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1
```

## Плагин включён (тут возникает 404):
![image](https://user-images.githubusercontent.com/20075333/166171403-f02822e4-7555-44bc-936f-fda184236449.png)
```sql
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts
WHERE 1=1
AND ( 0 = 1 )
AND ((wp_posts.post_type = 'post'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'private')))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1
```

**Comment by kagg-design** [comment]
Привет! Спасибо за репорт. Я пофиксил это в 5.5.0. Выпустим на днях.
