### ISSUE TITLE
Отключить преобразование имён файлов

### ISSUE THREAD

**Issue by NickBTraveler** [mihdan/cyr2lat#119]
Здравствуйте! Подскажите пожалуйста, как корректно отключить в плагине преобразование имён файлов в нижний регистр?

**Comment by NickBTraveler** [comment]
Строка 309 в
cyr2lat/src/php/class-main.php

**Comment by mihdan** [comment]
А можно поинтересоваться для чего вам это? Может имеет смысл сделать настройку

**Comment by NickBTraveler** [comment]
Использую автоматизированный импорт изображений на сайт - по названию они автоматически привязываются к постам по метаполю с именем. Исторически так сложилось, что имена у файлов не переводились в нижний регистр, а данные в метаполе нельзя переводить в нижний, потому, когда подключил плагин транслитерации, сломалась автоматическая привязка изображений - система искала файлы по данным из метаполя и не находила, так как они в нижнем регистре.

Никита Батищев
Руководитель, гид, инструктор
Telegram: https://t.me/nickbtraveler [https://t.me/nickbtraveler]
***@***.*** [https://instagram.com/nickbtraveler]
Яндекс Дзен: https://zen.yandex.ru/ims [https://zen.yandex.ru/ims]
Сайт / Статьи и обзоры: inmysight.ru [https://inmysight.ru/]
YouTube: Мой канал [https://www.youtube.com/channel/UCn7nGsNtM-VnjSQJCxBgsqw]
Услуги гида: nickbguide.ru [https://nickbguide.ru]
ИТ-услуги: inmysight.ru/it [https://inmysight.ru/it]
Эл. ***@***.*** ***@***.***
Тел., WhatsApp: +7-909-835-9869
On 13.05.2022 9:12:32, Mikhail Kobzarev ***@***.***> wrote:
А можно поинтересоваться для чего вам это? Может имеет смысл сделать настройку

**Comment by mihdan** [comment]
Для решения данного вопроса попробуйте использовать соответствующий фильтр, который отключает перевод имен файлов в нижний регистр:

```php
<?php
add_filter( 'ctl_pre_sanitize_filename', '__return_true' );
```
