### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in

### ISSUE THREAD

**Issue by Veltix** [mihdan/cyr2lat#122]
I found errors: Cyr 2 lat not working at all...

1) error:
htdocs/wp-content/plugins/cyr2lat/src/php/background-processes/class-post-conversion-process.php:212
Stack trace:
#0 /htdocs/wp-includes/class-wp-hook.php(307): Cyr_To_Lat\Post_Conversion_Process->filter_post_locale('et')
#1 /htdocs/wp-includes/plugin.php(191): WP_Hook->apply_filters('et', Array)
#2 /htdocs/wp-includes/l10n.php(35): apply_filters('locale', 'en_US')
#3 /htdocs/wp-content/plugins/cyr2lat/src/php/Settings/Settings.php(146): get_locale()
#4 /htdocs/wp-content/plugins/cyr2lat/src/php/class-main.php(372): Cyr_To_Lat\Settings\Settings->get_table()
#5 /htdocs/wp-content/plugins/cyr2lat/src/php/background-processes/class-post-conversion-process.php(6 in /htdocs/wp-content/plugins/cyr2lat/src/php/background-processes/class-post-conversion-process.php on line 212

2)error:
[13-Jul-2022 20:28:05 UTC] Cyr To Lat: Post slug converted: дополнительные-принадлежности-2 => dopolnitelnye-prinadlezhnosti-2
[13-Jul-2022 20:28:05 UTC] Cyr To Lat: Cannot convert attachment file for attachment id: 9247

**Comment by kagg-design** [comment]
Why does stack trace contain links to other issues?

I close this issue as non-readable.
