### ISSUE TITLE
Имеет смысл добавить фильтр для работы на фронте

### ISSUE THREAD

**Issue by artikus11** [mihdan/cyr2lat#131]
Столкнулся с тем, что при использовании функции `sanitize_title` на фронте, например при выводе полей в форме, как на картинке
![image](https://github.com/mihdan/cyr2lat/assets/16116688/c835d312-f57a-48bd-b2df-caf17ca17a4c)

Функция не работает, так как стоит [проверка на фронт](https://github.com/mihdan/cyr2lat/blob/master/src/php/class-main.php#L136) нужен какой то способ обойти эту проверку или фильтр, чтобы отключать эту проверку на нужных страницах

**Comment by kagg-design** [comment]
Добавил фильтр ctl_allow. См. readme.txt. Выйдет в 6.0.0.
