### ISSUE TITLE
[Bug] Символ `ʼ`, присуствующий в заголовке, не заменяется пустой строкой в slug

### ISSUE THREAD

**Issue by IvanZhuck** [mihdan/cyr2lat#145]
Символ `ʼ` (юникод U+02BC), присуствующий в заголовке, не заменяется пустой строкой в slug.

**Как воспроизвести баг:**

1. Развернуть WP на русском языке
2. Установить и активировать Cyr-To-Lat 6.0.5
3. Создать запись с заголовком "Пхʼнглуи мглвʼнафх Ктулху Рʼльех вгахʼнагл фхтагн"
4. Запись опубликуется со слагом "phʼnglui-mglvʼnafh-ktulhu-rʼleh-vgahʼnagl-fhtagn"

**Ожидаемое поведение:**

Из заголовка  "Пхʼнглуи мглвʼнафх Ктулху Рʼльех вгахʼнагл фхтагн" создается слаг "phnglui-mglvnafh-ktulhu-rleh-vgahnagl-fhtagn"

**Comment by IvanZhuck** [comment]
Оказалось, что это баг самого WP, создал соответствующий тикет: https://core.trac.wordpress.org/ticket/59691

**Comment by mihdan** [comment]
Да, эти замены производит ядро. Аналогичная проблема и со знаком №.
