### ISSUE TITLE
Пожелание – конвертировать ссылки автоматически в нижний регистр

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#25]
https://wordpress.org/support/topic/отлично-144/

**Comment by kagg-design** [comment]
Я предлагаю закрыть эту проблему. По крайней мере с WP 2.3 (который обозначен у нас как младшая поддерживаемая версия), WP конвертирует слаги в нижний регистр, если они в UTF-8 и присутствует расширение `mbstring`.

**Comment by mihdan** [comment]
Согласен

**Comment by mihdan** [comment]
Открыто в связи с тем, что имена файлов НЕ переводятся автоматом в нижни регистр, только ярлыки записей.

**Comment by mihdan** [comment]
https://github.com/mihdan/cyr2lat/pull/70
