### ISSUE TITLE
Не находит переводы (языковые файлы)

### ISSUE THREAD

**Issue by seredniy** [mihdan/cyr2lat#26]
![image](https://user-images.githubusercontent.com/11270429/52410982-d5d51d80-2ae2-11e9-8ca9-e34b325ebd6b.png)

Вот скрин query monitor. Переводы обновлены

**Comment by kagg-design** [comment]
Это не ошибка, а нормальная работа ядра WP. Функция `load_plugin_textdomain()` сначала ищет языковые файлы в `wp-content/languages/plugins`, а уже потом - в папке плагина.
