### ISSUE TITLE
Конфликт с Lingotek Translation

### ISSUE THREAD

**Issue by SergeyBiryukov** [mihdan/cyr2lat#29]
Написали в ВК:

> Плагин Cyr-To-Lat конфликтует с плагином Lingotek Translation. Последний перестает корректно работать. Разработчикам Lingotek я уже сообщил, а тебе пишу тут. Надеюсь, поможет. Удачи!

Из подробностей только это:

> Rolf Diedrichs (Lingotek Support)
> Feb 13, 4:17 AM MST
> 
> Hi Valery,
> 
> Suddenly it makes sense while reading about the plugin. The URL of the post/page gets changed and Lingotek does not have a way to send the callback. (At least that is what I think happened)
> 
> Regards,
> Rolf

**Comment by mihdan** [comment]
попробуем понять что за плагин @SergeyBiryukov

**Comment by mihdan** [comment]
Я так понял плагин тот переводит урлы, тогда зачем им cyr2lat. 
 нашем плагине есть фильтр `ctl_pre_sanitize_title` для отключения функционала

**Comment by mihdan** [comment]
Мы добавили условия, чтобы плагин работал только на экранах редактирования, а не по всей админке, ну и фильтр `ctl_pre_sanitize_title` поможет.
