### ISSUE TITLE
При переходе с Rus-To-Lat меняются классы меню

### ISSUE THREAD

**Issue by SergeyBiryukov** [mihdan/cyr2lat#30]
Из Slack:
> ...Переделываю сайт. Там был когда-то Rus-to-Lat, но я его давно заменил на Cyr-to-Lat. Это меню редактировал (не помню, создавал ли или было, но по-моему и создавал я) уже давненько. Но точно уже с Cyr-to-Lat.
>И вот сегодня я обновил и плагин и WP, опять отредактировал меню, и оно у меня поплыло.
> После редактирования меню поменялся его класс, который формируется из названия меню.
> Меню называется «Верхнее меню». Класс был `menu-verxnee-menyu-container`, а стал `menu-verhnee-menyu-container`.  (verxnee — verhnee)
> И id'шки `ul` также полетели.

Если классы меню уже были на латинице — при редактировании они не должны меняться (как и ярлыки записей).

**Comment by mihdan** [comment]
Классы же генерятся динамически я так понимаю. В данной ситуации достаточно в настройках плагина в русской таблице вернуть обратно транслит на тот, что был у человека раньше и который явно не по ГОСТ.

А вот почему оно поменялось в принципе - посмотрим

**Comment by mihdan** [comment]
- https://github.com/mihdan/cyr2lat/commit/ca11d54442e96d340c7b91e8a472d797cffa2b5c
- https://github.com/mihdan/cyr2lat/commit/ebfc34ef9ab2ea5c9acfe8ffdcc78848a21c9404
