### ISSUE TITLE
Выбор языка

### ISSUE THREAD

**Issue by granatmedia** [mihdan/cyr2lat#34]
Привет,

столкнулся с проблемой.
Админка на русском, сайт на украинском. Транслитерация идет как с русского.
Добавьте возможность выбора языка для транслитерации.

Спасибо.

https://wordpress.org/support/topic/%D0%B2%D1%8B%D0%B1%D0%BE%D1%80-%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0/#post-11304107

**Comment by SergeyBiryukov** [comment]
Если перед закрытием тикета [где-было обсуждение](https://wordpress.org/support/topic/выбор-языка/#post-11446195) — стоит добавить его и сюда для истории:

> Мы тут посовещались и решили, что сейчас сделано правильно – для перевода берётся язык сайта (он указывается в общих настройках).
> 
> В вашем кейсе нужно выбрать язык сайта украинский в общих настройках, а у конкретного пользователя выбрать любой другой язык.
> 
> Это не поломает ничего и будет работать как вам надо.
