### ISSUE TITLE
Добавить латышский язык

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#39]

**Comment by mihdan** [comment]
Посовещались и решили, что это в ядре должно быть, в `remove_accents()`, а не в плагине: https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-includes/formatting.php#L1550

**Comment by kagg-design** [comment]
Я протестировал на чистом WP 5.1 с блочным редактором. Попытка создать запись с заголовком

A Ā B C Č D E Ē F G Ģ H I Ī J K Ķ L Ļ M N Ņ O P R S Š T U Ū V Z Ž a ā b c č d e ē f g ģ h i ī j k ķ l ļ m n ņ o p r s š t u ū v z ž

Создает такой слаг
a-a-b-c-c-d-e-e-f-g-g-h-i-i-j-k-k-l-l-m-n-n-o-p-r-s-s-t-u-u-v-z-z-a-a-b-c-c-d-e-e-f-g-g-h-i-i-j-k-k-l-l-m-n-n-o-p-r-s-s-t-u-u-v-z-z

Так что наш плагин тут не нужен.
