### ISSUE TITLE
Добавить ресурсы плагина

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#4]
1. [x] Придумать шапку (banner-772x250.png)
2. [x] Придумать лого (icon-128x128.png и icon.svg)
3. [x] Отрисовать шапку и лого (svg)
4. [x] Добавить скриншоты (screenshot-1.png ... )

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by mihdan** [comment]
https://github.com/mihdan/cyr2lat/commit/13d5c31f972b5ce2aaf7fbc18ac23d6cb1162ce8

**Comment by Otshelnik-Fm** [comment]
На картинке https://ps.w.org/cyr2lat/assets/banner-772x250.png?rev=2022835 описание скрина - 3 строки на английском, а справа скрин его настроек - на русском. Убрать наверно надо это расхождение. 

> Добавить скриншоты (screenshot-1.png ... )
так и не добавили...

**Comment by mihdan** [comment]
TODO:
1. Добавить скриншоты
2. В шапке скрин добавить на английском

@Otshelnik-Fm спасибо

**Comment by mihdan** [comment]
https://github.com/mihdan/cyr2lat/commit/fb6018b544c8c05e8acc65c3785cc1e65b838942
