### ISSUE TITLE
Сделайте мне и транслит со Шведского

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#49]

**Comment by SergeyBiryukov** [comment]
И давно шведский перешёл на кириллицу?)

Если нужно какие-то символы превращать в ASCII-эквиваленты — лучше создать тикет в WordPress для добавления их в [remove_accents()](https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-includes/formatting.php#L1550).

**Comment by mihdan** [comment]
Вопрос по большому счету решается через фильтр `ctl_table`
