### ISSUE TITLE
Cyrillic variations disappearing in woocommerce

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#55]
Hi there!

Please, help me to solve this issue with my cyrillic product variations ..

Then I activate plugin “Cyr to Lat enhanced” .. all my variations somehow disappear ..

Please see the screenshots
before I activated “Cyr to Lat enhanced”:
https://prnt.sc/let1vx

after:
https://prnt.sc/let23r

Thank you!

The page I need help with: https://www.specialistweb.info/tvoiprotein/?product=vp-lab-l-carnitine-500-ml

Источник - https://wordpress.org/support/topic/cyrillic-variations-disappearing-in-woocommerce/
Этот баг в форке, но cyr2lat так же подвержен

**Comment by zevilz** [comment]
Если ярлыки значений атрибутов в кириллице, то после активации плагина и при сохранении вариаций все атрибуты сбрасываются на "Любой атрибут ..."

**Comment by mihdan** [comment]
https://github.com/mihdan/cyr2lat/commit/97bd51527427ca78ba9f0f07345586ae3fcbc0ea
