### ISSUE TITLE
WordPress 5.2+ сообщает об ошибке

### ISSUE THREAD

**Issue by Yuribtr** [mihdan/cyr2lat#63]
Здравствуйте,
в работе плагина проблем не замечено было, но после обновления Wordpress 5.2.1 на администраторский адрес пришло сообщение об автоматическом обнаружении ошибки. В конце вот такой вот лог:

Подробности ошибки
===================================
Ошибка с типом E_ERROR возникла на строке 133 файла ...../wp-content/plugins/cyr2lat/includes/class-cyr-to-lat-main.php. 
Сообщение об ошибке: Maximum execution time of 30 seconds exceeded

**Comment by mihdan** [comment]
Спасибо за сигнал, разберемся. У вас установлен, настроен, включен какой-то дебаггер на сервере? Какой хостер?

**Comment by kagg-design** [comment]
Воспроизвести не удалось. Тяжёлого цикла в данном месте нет (просмотр массива не считается). Возможно, 30 секунд чисто случайно закончились именно в этом месте.

**Comment by mihdan** [comment]
Под шумок `debug_backtrace()` был немного убыстрён - https://github.com/mihdan/cyr2lat/commit/bf51712ff0860dfbc7b78a84d5a6062668d3ac49
