### ISSUE TITLE
Новые записи получают ярлык 'chernovik'

### ISSUE THREAD

**Issue by SergeyBiryukov** [mihdan/cyr2lat#65]
WordPress 5.2.2, чистая установка:
1. Создаю запись с заголовком «Тест».
2. Получаю ярлык `тест` (`%d1%82%d0%b5%d1%81%d1%82`), как и ожидал.

WordPress 5.2.2 с Cyr-To-Lat 4.2.1:
1. Создаю запись с заголовком «Тест».
2. Получаю ярлык `chernovik`. Если не поправить вручную, после публикации таким и остаётся. Видимо, берётся из `__( 'Auto Draft' )` в [`get_default_post_to_edit()`](https://core.trac.wordpress.org/browser/tags/5.2/src/wp-admin/includes/post.php?marks=664#L645).

Именно об этом я говорил, когда предупреждал, что код `ctl_sanitize_post_name()` — это примерный вариант, который стоит тщательно протестировать перед релизом, а не выкладывать как есть :)

**Comment by SergeyBiryukov** [comment]
Основная загвоздка в том, что в Gutenberg пока нет аналога `sanitize_title()`, фильтр срабатывает только в момент публикации: https://github.com/WordPress/gutenberg/issues/12907.

`ctl_sanitize_post_name()` пытается обойти эту проблему с помощью фильтра `wp_insert_post_data`, который срабатывает при каждом сохранении. Нужно дополнить текущее решение, чтобы сохранить правильное поведение: значение `post_name` должно продолжать обновляться из `post_title`, пока запись не опубликована.

**Comment by mihdan** [comment]
В 5.2.2 создаю запись с названием "тест", жмакаю сохранить, получаю в слаге "тест" (хотя в 5й версии тут бул перевод), нажимаю "Опубликовать", получаю слаг "test".

Или у тебя авточерновик? @SergeyBiryukov

**Comment by kagg-design** [comment]
@SergeyBiryukov я не могу воспроизвести эту проблему на чистом 5.2.2. Всё работает, как часы.
