### ISSUE TITLE
The WooCommerce nonce_user_logged_out filter is overwriting 

### ISSUE THREAD

**Issue by oscargare** [mihdan/cyr2lat#66]
Hi,
The first: nice code ;)

I noticed that the plugin add the **nonce_user_logged_out** filter. This filter could cause issues with other plugins, like WooCommerce. 
WooCommerce adds a nonce_user_logged_out filter and cry2lat overwrites it. I think that adding the filter is no-needed.

The class _Cyr_To_Lat_Converter_ instances an object of _Cyr_To_Lat_Post_Conversion_Process_, and an object of _Cyr_To_Lat_Term_Conversion_Process_ in the __contruct. 

_Cyr_To_Lat_Post_Conversion_Process_ and _Cyr_To_Lat_Term_Conversion_Process_ extend of _WP_Async_Request_, which adds the **nonce_user_logged_out** filter on the **init** hook; but _Cyr_To_Lat_Converter_ only uses the instances in _wp_admin_. This is creating PHP sessions in the frontend and it is overwriting the WooCommerce nonce based on session cookie.

Why not instance the objects in the admin_init hook?

```
/**
	 * Cyr_To_Lat_Converter constructor.
	 *
	 * @param Cyr_To_Lat_Main                    $main              Plugin main class.
	 * @param Cyr_To_Lat_Settings                $settings          Plugin settings.
	 * @param Cyr_To_Lat_Post_Conversion_Process $process_all_posts Plugin settings.
	 * @param Cyr_To_Lat_Term_Conversion_Process $process_all_terms Plugin settings.
	 * @param Cyr_To_Lat_Admin_Notices           $admin_notices     Plugin settings.
	 */
	public function __construct(
		$main, $settings, $process_all_posts = null, $process_all_terms = null, $admin_notices = null
	) {
		$this->main              = $main;
		$this->settings          = $settings;
		$this->option_group      = Cyr_To_Lat_Settings::OPTION_GROUP;
		$this->process_all_posts = $process_all_posts;
		$this->process_all_terms = $process_all_terms;

		$this->admin_notices = $admin_notices;
		if ( ! $this->admin_notices ) {
			$this->admin_notices = new Cyr_To_Lat_Admin_Notices();
		}

		$this->init_hooks();
	}

	/**
	 * Init class hooks.
	 */
	public function init_hooks() {
		add_action( 'admin_init', array( $this, 'instance_conversion_process' ), 5 );
		add_action( 'admin_init', array( $this, 'process_handler' ) );
		add_action( 'admin_init', array( $this, 'conversion_notices' ) );
	}

	/**
	 * Instances the conversion process objects.
	 */
	public function instance_conversion_process() {
		if ( ! $this->process_all_posts ) {
			$this->process_all_posts = new Cyr_To_Lat_Post_Conversion_Process( $main );
		}

		if ( ! $this->process_all_terms ) {
			$this->process_all_terms = new Cyr_To_Lat_Term_Conversion_Process( $main );
		}
	}
```
Or check if is_admin before instance the objects:

```
$this->process_all_posts = $process_all_posts;
		if ( ! $this->process_all_posts && is_admin() ) {
			$this->process_all_posts = new Cyr_To_Lat_Post_Conversion_Process( $main );
		}

		$this->process_all_terms = $process_all_terms;
		if ( ! $this->process_all_terms && is_admin() ) {
			$this->process_all_terms = new Cyr_To_Lat_Term_Conversion_Process( $main );
		}

```
Thanks for your work :)

**Comment by kagg-design** [comment]
Hi Oscar,

Thank you for kind words, very appreciated. Apologies for a late answer, I just missed your comment.

We have decided to remove everything related to sessions and `nonce_user_logged_out` from my fork of [wp-background-processing](https://github.com/kagg-design/wp-background-processing/commit/75142e7269c5df90ad3699031b35028975980258). This was done on Jun, 22.

On the next day we published a new version of cyr2lat, 4.2.1, with modified composer files to reflect changes in wp-background-processing.

You are right, this could cause problems with WooCommerce, and was wrong by essense, as we pass cookies in `WP_Async_Request::`.

Thank you again for code review, we will be pleased to hear from you at any time.

Igor.
