### ISSUE TITLE
Предусмотреть отмену транслитерации при перегенерации миниатюр

### ISSUE THREAD

**Issue by campusboy87** [mihdan/cyr2lat#67]
Использую WP CLI для перегенерации миниатюр, команда
```
wp media regenerate
```
Из-за плагина все файлы транслитерируются, что ведёт к битым ссылкам в статьях, где были вставлены старые изображения со старыми именами.

Скорее всего та же проблема будет и при использовании подобных плагинов по перегенерации миниатюр.

**Comment by mihdan** [comment]
При перегенерации миниатюр можно отключат плагин cyr2lat, например:

`wp media regenerate --skip-plugins=cyr2lat`

**Comment by mihdan** [comment]
Нужно добавить это в документацию и FAQ

**Comment by kagg-design** [comment]
Resolved in 5.1.
