### ISSUE TITLE
Заголовок файла на русском языке

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#73]
Здравствуйте.
Столкнулся с небольшой проблемой. Есть сайт, на который загружают прайс-листы. Названия файлов на русском языке.

При редактировании страницы и прямом переносе файла в блок транслируется заголовок.
Прайс от 13.05.19 (Скачать) -> Prajs-ot-13.05.19 (Скачать)
Каждый раз приходится редактировать название заголовка, что несколько неудобно.

Если предварительно загружать файлы в “Библиотеку файлов”, заголовок не меняется и остаётся на русском.

https://wordpress.org/support/topic/%d0%b7%d0%b0%d0%b3%d0%be%d0%bb%d0%be%d0%b2%d0%be%d0%ba-%d1%84%d0%b0%d0%b9%d0%bb%d0%b0-%d0%bd%d0%b0-%d1%80%d1%83%d1%81%d1%81%d0%ba%d0%be%d0%bc-%d1%8f%d0%b7%d1%8b%d0%ba%d0%b5/#post-11986097

**Comment by kagg-design** [comment]
Не удаётся воспроизвести проблему, тикет на wp.org закрыт.
