### ISSUE TITLE
Перекодировать ссылки для woocommerce

### ISSUE THREAD

**Issue by mastaru** [mihdan/cyr2lat#76]
Мне нужно перекодировать все ссылки на woocommerce, надо что бы "щ" было не "shh", а "sh".
Я попробовал поменять символ в настройках плагина в админке, и нажать на кнопку конвектировать существующие ярлыки, но появилась ошибка
Cyr To Lat не нашёл существующих ярлыков записей для конвертации.

Тогда я в function.php добавил 
add_filter( 'ctl_table', 'my_cyr_to_lat_table' );
function my_cyr_to_lat_table($ctl_table) {
	$ctl_table['щ'] = 'SH';
	$ctl_table['щ'] = 'sh';
	return $ctl_table;
}
А потом через WP-CLI выполнил команду
wp cyr2lat regenerate [—post_type='product'] [—post_status='publish']

Но опять же, не чего не произошло...

Версия cyr-to-lat 4.3.2
WordPress 5.3.2

**Comment by mihdan** [comment]
"ссылки на woocommerce" это слаги товаров?

**Comment by mastaru** [comment]
> "ссылки на woocommerce" это слаги товаров?

да

**Comment by mastaru** [comment]
Это возможно сделать?

**Comment by mihdan** [comment]
У вас слаги уже переведены в латинницу были?

**Comment by mastaru** [comment]
Да

**Comment by mihdan** [comment]
Плагине не трогает уже переведенные строки, иначе все ссылки на сайте сломаются, например, которые были в тексте записей указанны. Была идея добавить `--force`, но отказались, так как будет лишь куча проблем. А свою таблицу добавить или поменять имеющуюся в админке сейчас - не составляет труда.

**Comment by mastaru** [comment]
А нет какого-нибудь костыля? Я просто сайт переношу с сохранением ссылок и там щ указанно как ssh, а не как sh. Можно ли все слаги как-нибудь сбросить и обработать по новой?

**Comment by mihdan** [comment]
Какой язык сайта указан? И в какой таблице меняете?

**Comment by mastaru** [comment]
Язык русский. Таблица, видимо ISO9

**Comment by mastaru** [comment]
Может через WP-CLI есть какой-нибудь костыль? Или можно создать отдельный php файл с костылём и запустить его через браузер?

**Comment by mastaru** [comment]
Меня просто смущает название функции в WP-CLI regenerate, т.е. это ПЕРЕгенерация, т.е. функция исходя из названия должна трогать уже переведенные строки

**Comment by mastaru** [comment]
Всё решил проблему своим костылём. Создал страницу которая перегенирирует при переходе на неё. Вот код страницы:
`<?
/*
Template Name: Генерация
*/
get_header();?>
<?
$iso = array(
            "Є"=>"YE","І"=>"I","Ѓ"=>"G","і"=>"i","№"=>"#","є"=>"ye","ѓ"=>"g",
            "А"=>"A","Б"=>"B","В"=>"V","Г"=>"G","Д"=>"D",
            "Е"=>"E","Ё"=>"YO","Ж"=>"ZH",
            "З"=>"Z","И"=>"I","Й"=>"Y","К"=>"K","Л"=>"L",
            "М"=>"M","Н"=>"N","О"=>"O","П"=>"P","Р"=>"R",
            "С"=>"S","Т"=>"T","У"=>"U","Ф"=>"F","Х"=>"X",
            "Ц"=>"C","Ч"=>"CH","Ш"=>"SH","Щ"=>"SH","Ъ"=>"'",
            "Ы"=>"Y","Ь"=>"","Э"=>"E","Ю"=>"YU","Я"=>"A",
            "а"=>"a","б"=>"b","в"=>"v","г"=>"g","д"=>"d",
            "е"=>"e","ё"=>"yo","ж"=>"zh",
            "з"=>"z","и"=>"i","й"=>"j","к"=>"k","л"=>"l",
            "м"=>"m","н"=>"n","о"=>"o","п"=>"p","р"=>"r",
            "с"=>"s","т"=>"t","у"=>"u","ф"=>"f","х"=>"x",
            "ц"=>"c","ч"=>"ch","ш"=>"sh","щ"=>"sh","ъ"=>"",
            "ы"=>"y","ь"=>"","э"=>"e","ю"=>"yu","я"=>"a",
            "—"=>"-","«"=>"","»"=>"","…"=>""
        );
$products = new WP_Query(['post_type'=>'product','posts_per_page'=>-1]);
if(!empty($products)) {
foreach($products->posts as $product) {
	wp_update_post(['ID' => $product->ID,'post_name' => strtr($product->post_title, $iso)]);
		echo $product->post_title . ' '. $product->post_name . '<br>';
	}
}
?>
<?get_footer();?>`

**Comment by mihdan** [comment]
Жаль, а мы только хотели заняться вопросом более детально. Но выходные вроде как.

**Comment by mastaru** [comment]
Не, ну вы допилите все таки) Я же не один могу с такой проблемой столкнуться. У меня просто сроки горят, по-этому я и таким костылем могу воспользоваться. У Вас просто есть кнопка в админке regenerate вроде, которая по идеи должна это делать, но она не работает(.

**Comment by mihdan** [comment]
Эта кнопка генерить из русских слагов латинские, когда их ооочень много - юзает я wp-cli. Хотя сейчас и кнопка это делает неплохо на фоне. Старые урлы, уже переведённые в латинницу, мы не трогали на тот случай, если пользователи перешли к нам из другого форка и плагина, где таблица символов отличается и не работал редирект.

**Comment by mastaru** [comment]
Ну в таком случаи кнопка должна называться просто генерация. Перегаенерация подразумевает что все ссылки в любом случаи должны быть переделаны. 

Ну и опять же, зачем нужна таблица символов в админке в которой можно изменить кодирование? Откуда я знаю как изначально переводиться тот или иной символ? 

Т.е. у меня сначала есть url с русскими символами, я его хочу переделать на латиницу, я скачиваю плагин которое это делает, он перекодирует, я хочу изменить немного кодировку, вижу в админке таблицу, изменяю символ, жму кнопку regenerate и ничего не происходит!  

А всё потому что плагин переводит ТОЛЬКО с кириллицы. Какой смысл в этой кнопки? 

Т.е по Вашей задумке я должен перед тем как перевести все ссылки в латиницу, я должен зайти в исходный код плагина и посмотреть как он будет переводить? В этом случаи я бы сразу поменял кодировку прям в коде, зачем нужна эта таблица в админке?
