### ISSUE TITLE
Обновление 4.3.3 сломало url страниц опций ACF

### ISSUE THREAD

**Issue by ijakparov** [mihdan/cyr2lat#78]
После обновление, страницы опций ACF не транслитирируются.

**Comment by mihdan** [comment]
Что за страницы опций?

**Comment by mihdan** [comment]
Обсудить вопрос можно у нас в чате https://t.me/cyr2lat

**Comment by mihdan** [comment]
@ijakparov как с 4.3.4?

**Comment by ijakparov** [comment]
> @ijakparov как с 4.3.4?

Пофиксилось, спасибо.

**Comment by mihdan** [comment]
@ijakparov ok
