### ISSUE TITLE
Обработка ошибки работы wp_remote_post()

### ISSUE THREAD

**Issue by zlex** [mihdan/cyr2lat#85]
Вызов \Cyr_To_Lat\KAGG\WP_Background_Processing\WP_Background_Process::dispatch() возвращает результат работы wp_remote_post(), который никак не обрабатывается. В некоторых случаях может возникать ошибка отправки данных через wp_remote_post(), например, ошибка 401 Unauthorized в случае наличия Basic-авторизации на тестовом сервере или для /wp-admin/.

Вызов dispatch() происходит в двух местах:
\Cyr_To_Lat\Converter::convert_existing_post_slugs()
\Cyr_To_Lat\Converter::convert_existing_term_slugs()

Ошибка может возникать при нажатии кнопки "_Конвертировать существующие ярлыки_" на странице настроек плагина, при наличии ошибки этот функционал не работает. В идеале, желательно выводить информацию об ошибке работы wp_remote_post() в интерфейс и в лог ошибок.

**Comment by kagg-design** [comment]
Не знаю, зачем эту тему обсуждать, с Basic Auth радостно не работает REST, невозможно сохранить новый пост в Block Editor.

**Comment by kagg-design** [comment]
Там асинхронный `wp_remote_post()`, с `'blocking'  => \false,` в аргументах. Он всегда возвращает

```
[
	'headers'       => [],
	'body'          => '',
	'response'      =>
		[
			'code'    => false,
			'message' => false,
		],
	'cookies'       => [],
	'http_response' => null,
];
```

Анализировать там нечего.

**Comment by kagg-design** [comment]
Мы решим эту проблему позже, когда появится динамический progress bar фонового процесса, с возможностью отмены.
