### ISSUE TITLE
Поддержка WPML

### ISSUE THREAD

**Issue by mihdan** [mihdan/cyr2lat#9]
Посотрудничать с разработчиками WPML, чтобы полностью поддерживать их продукт

https://wpml.org/documentation/theme-compatibility/go-global-program/

**Comment by mihdan** [comment]
@SergeyBiryukov @kagg-design может стоит отключать плагин, если активен WPML?

**Comment by kagg-design** [comment]
А в чём проблема с WPML?

**Comment by mihdan** [comment]
В WPML есть встроенный метот перевода слагов, который будет конфликтовать с cyr2lat, предлагаю отключать функционал cyr2lat, если эта опция WPML активна.

**Comment by kagg-design** [comment]
Попробую решить в ближайшие выходные, там не должно быть сложно.

**Comment by mihdan** [comment]
Сертификат благодаря @kagg-design получен.

![WPML Certificate](https://ps.w.org/cyr2lat/assets/Cyr-To-Lat---WPML-Compatibility-Certificate-240x250.png)
