### ISSUE TITLE
Ломаются страницы категорий и тегов с кириллическим URL

### ISSUE THREAD

**Issue by zaprudin** [mihdan/cyr2lat#95]
После активации плагина ломаются страницы тегов и категорий с кириллическим URL (типа site.ru/category/имя-категории) - выдают ошибку 404. После отключения плагина снова все работает.
Если есть необходимость сохранить для старых категорий старые кириллические URL, приходится искать другой плагин.

Заметил это на существующем большом сайте WP 5.6.2, подтвердилось и на пустом WP 5.7 со стандартной темой и отключенными другими плагинами.
Версия плагина 4.6.4

**Comment by mihdan** [comment]
Подождите новую версию, там будет выбор того, что вы хотите переводить в транслит

**Comment by kagg-design** [comment]
Между прочим.
1. Чиcтый WP.
2. Posts->Categories.
3. Uncategorized->View.
404

Баг в WP.

Лечится заходом на страницу постоянных ссылок.

**Comment by kagg-design** [comment]
Пофиксил в 5.1, скоро опубликуем.

@mihdan ушёл я наконец-то от debug_backtrace! https://github.com/mihdan/cyr2lat/commit/5058786af0d7c344676eacd45b8f7fc926761d23
