### ISSUE TITLE
Notice iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//TRANSLIT//IGNORE' is not allowed

### ISSUE THREAD

**Issue by AlexL-JWA** [mihdan/cyr2lat#99]
wp-content/plugins/cyr2lat/src/php/class-main.php:349
iconv()
wp-content/plugins/cyr2lat/src/php/class-main.php:349
Cyr_To_Lat\Main->transliterate()
wp-content/plugins/cyr2lat/src/php/class-main.php:223
Cyr_To_Lat\Main->sanitize_title()
wp-includes/class-wp-hook.php:292
apply_filters('sanitize_title')
wp-includes/formatting.php:2188
sanitize_title()
wp-admin/includes/menu.php:62

![image](https://user-images.githubusercontent.com/11867799/119223195-b3733c80-bb00-11eb-8788-280e9ceeb8a0.png)

**Comment by kviron** [comment]
Similar problem

**Comment by kagg-design** [comment]
После изучения проблемы, убрал код с iconv() как устаревший. Выйдет в 5.1.0.
